### ISSUE TITLE
foreign_key_lookups doesn't work for me

### ISSUE THREAD

**Issue by ygidtu** [coleifer/flask-peewee#171]
I'm running the flask_peewee example, but the foreign_key_loopups doesn't work. 
And when I tried to add new message to it. I can't select any of users in database

- flask: 0.12.2
- flask-peewee 3.0.0
- peewee 3.5.0
- anaconda3 5.2.0

![peewee](https://user-images.githubusercontent.com/29178828/42306002-eef9bd3a-805f-11e8-985c-2fc2550828a2.png)
![peewee1](https://user-images.githubusercontent.com/29178828/42306086-353efd14-8060-11e8-9a57-0b99678d42ff.png)

**Comment by coleifer** [comment]
Thanks for reporting, fixed.

**Comment by coleifer** [comment]
3.0.1 pushed.

**Comment by ygidtu** [comment]
Thanks for your work, I updated flask_peewee to 3.0.1. But it seems still not working.
And when I tried to click on User id under message editing page, I got some KeyError
![qq20180706-171541](https://user-images.githubusercontent.com/29178828/42370890-843c5c32-8140-11e8-8f8a-389e66de259e.png)
![qq20180706-171632](https://user-images.githubusercontent.com/29178828/42370894-876fd1ae-8140-11e8-9407-4efa7da6298c.png)
<img width="665" alt="qq20180706-171605 2x" src="https://user-images.githubusercontent.com/29178828/42370899-8a4b9912-8140-11e8-9698-dce140b65248.png">

**Comment by coleifer** [comment]
Apologies, 3.0.2 should *actually* fix the issue.

**Comment by coleifer** [comment]
This should fix the first issue regarding the use of "unicode()": 480cc1566e30603ef58081bd4ece5464e586f990

**Comment by coleifer** [comment]
It appears to be working for me now:

![s1531145809 57](https://user-images.githubusercontent.com/119974/42455822-e6be2bd2-8358-11e8-9cde-fe021c590fd7.png)
![s1531145817 98](https://user-images.githubusercontent.com/119974/42455823-e6ce813a-8358-11e8-90da-0c842288260d.png)

**Comment by alfonsodg** [comment]
Hello,

The problem persists, I just installed flask-peewee with virtualenv including:
peewee 3.6.4
flask-peewee 3.0.3
flask 1.02
and it does not do the visual relationship as described in the manual or as it should be seen in the example application

![seleccion_053](https://user-images.githubusercontent.com/861056/43328048-a9992ddc-9182-11e8-992f-43b0afaab204.png)
![seleccion_054](https://user-images.githubusercontent.com/861056/43328053-ae17f726-9182-11e8-857c-eeb83665cfc3.png)
![seleccion_055](https://user-images.githubusercontent.com/861056/43328062-b3c0784c-9182-11e8-8c4e-964e0dc49be1.png)
![seleccion_057](https://user-images.githubusercontent.com/861056/43328081-babd7a50-9182-11e8-894d-10a62dce1660.png)
![seleccion_056](https://user-images.githubusercontent.com/861056/43328088-be3a0a36-9182-11e8-8c11-dd1d273f491b.png)

**Comment by coleifer** [comment]
Thanks, this was a small outdated portion of the example app models, which defined a custom model label using `__unicode__()`, whereas newer peewee versions rely on `__str__()`. I've updated the example app models and verified that the labels are appearing correctly.

**Comment by alfonsodg** [comment]
Thank to you! You should know that your project is the only one that worked for me at the first installation, the rest of your recommendations have problems with peewee and so far I do not even want to make your examples work
